### ISSUE TITLE
Possibility of exporting a commonjs version?

### ISSUE THREAD

**Issue by abdul-alhasany** [origin-1/c8js#2]
Hi
I am working on a VSCode extension and trying to create code coverage for it. I can not use CLI because VSCode create a new instance and run the tests in that instance. So I am only left with Node API.

I tried to used this library, but because it is only ESM and VSCode is commonjs only, I could not import it and see if it resolve my issue.

Is there a plan to add commonjs build as well? I know it is frowned upon now but unfortunately that is the only way to work with VSCode extension development. 

Thanks in advance.

**Comment by fasttime** [comment]
Hi @abdul-alhasany, I am not familiar with VSCode extensions, but it shouldn't be difficult to load c8js from a CommonJS module with a dynamic import.

For example, you could have a CJS wrapper that looks like this:

```js
// c8js.cjs

async function c8js(command, args, options) {
    const { default: c8js } = await import('c8js');
    return await c8js(command, args, options);
};

c8js.report = async function(options) {
    const { report } = await import('c8js');
    return await report(options);
};

// ...other methods

module.exports = c8js;
```

And this could be required in the CJS module that interfaces the VSCode extension:

```js
// index.js
const c8js = require('./c8js.cjs');
```

All functions exported by c8js return a promise, so wrapping them in `async` functions in order to dynamically import the ESM module will not change the return type.

**Comment by abdul-alhasany** [comment]
Thanks for the advise. Unfortunately I am using typescript which transpiles dynamic imports into require.

I think I will just give up on coverage report for now.

**Comment by fasttime** [comment]
Version 0.6.0 exports a CommonJS module. Now you can do for example:

```js
const c8js = require('c8js');
const { report } = require('c8js');
```
